# Generated by Django 2.1.4 on 2018-12-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('url', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('votes_total', models.BigIntegerField()),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('icon', models.ImageField(upload_to='icons/%Y/%m/%d/')),
                ('body', models.TextField()),
            ],
        ),
    ]
